Write-Host "Removing Store Apps..."

$store_apps = @(
	"Microsoft.3DBuilder",
	"Microsoft.BingFinance",
	"Microsoft.BingNews"
	"Microsoft.BingSports",
	"Microsoft.BingWeather",
	"Microsoft.CommsPhone",
	"Microsoft.FreshPaint",
	"Microsoft.GetHelp",
	"Microsoft.Getstarted",
	"Microsoft.Messaging",
	"Microsoft.MicrosoftOfficeHub",
	"Microsoft.MicrosoftSolitaireCollection",
	"Microsoft.MicrosoftStickyNotes",
	"Microsoft.MinecraftUWP",
	"Microsoft.NetworkSpeedTest",
	"Microsoft.Office.OneNote",
	"Microsoft.Office.Sway",
	"Microsoft.OneConnect",
	"Microsoft.People",
	"Microsoft.Print3D",
	"Microsoft.SkypeApp",
	"Microsoft.Windows.Photos",
	"Microsoft.WindowsAlarms",
	"Microsoft.WindowsCalculator",
	"Microsoft.WindowsCamera",
	"Microsoft.WindowsFeedbackHub",
	"Microsoft.WindowsMaps",
	"Microsoft.WindowsPhone",
	"Microsoft.WindowsSoundRecorder",
	"Microsoft.Xbox.TCUI",
	"Microsoft.XboxApp",
	"Microsoft.XboxGamingOverlay",
	"Microsoft.XboxIdentityProvider",
	"Microsoft.YourPhone",
	"Microsoft.ZuneMusic",
	"Microsoft.ZuneVideo",
	"microsoft.windowscommunicationsapps",
	"king.com.BubbleWitch3Saga",
	"king.com.CandyCrushSodaSaga",
	"king.com.*",
	"*Autodesk*",
	"*Dell*",
	"*Facebook*",
	"*Keeper*",
	"*MarchofEmpires*",
	"*Netflix*",
	"*Plex*",
	"*Twitter*",
	"ActiproSoftwareLLC.562882FEEB491",
	"46928bounde.EclipseManager",
	"PandoraMediaInc.29680B314EFC2",
	"D5EA27B7.Duolingo-LearnLanguagesforFree"
)

foreach ($app in $store_apps) {
	Get-AppxPackage -Name $app -AllUsers | Remove-AppxPackage
}
